name: deploy react App
on: push
jobs:
   test:
    runs-on: ubuntu-latest
    steps: 
    - name: get repository code
      uses: actions/checkout@v3
    - name: install dependecies
      run: npm ci # can install into ci
    - name: Test aplication
      run: npm run test
   lint:
      runs-on: ubuntu-latest
      steps: 
      - name: get repository code
        uses: actions/checkout@v3
      - name: install dependecies
        run: npm ci # can install into ci
      - name: lint aplication
        run: npm run lint
   build:
      runs-on: ubuntu-latest
      steps: 
      - name: get repository code
        uses: actions/checkout@v3
      - name: install dependecies
        run: npm ci # can install into ci
      - name: build aplication
        run: npm run build
      - name: deploy
        run: echo deploying...




  